version: '3.8'

services:
  # PostgreSQL database with PostGIS extension
  db:
    image: postgis/postgis:13-3.1
    container_name: miami-realestate-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: miami_realestate
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

  # Backend API service
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: miami-realestate-api
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: miami_realestate
      GOOGLE_MAPS_API_KEY: your_api_key_here
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app-network

  # Frontend client application
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: miami-realestate-client
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_MAPBOX_TOKEN: your_mapbox_token_here
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 